name: CI/CD - Deploy to AWS ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 906697541576.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t video-stylizer .

      - name: Tag Docker image for ECR
        run: docker tag video-stylizer:latest 906697541576.dkr.ecr.ap-south-1.amazonaws.com/video-stylizer-repo:latest

      - name: Push Docker image to ECR
        run: docker push 906697541576.dkr.ecr.ap-south-1.amazonaws.com/video-stylizer-repo:latest

      - name: Deploy ECS service (force new deployment)
        run: |
          aws ecs update-service --cluster video-stylizer-cluster --service video-stylizer-service --force-new-deployment